### ISSUE TITLE
Setting higher resolution doesn't work when recording video on pidog

### ISSUE THREAD

**Issue by ilyatregubov** [sunfounder/vilib#10]
Setting higher resolution doesn't work when recording video on pidog

Trying https://github.com/sunfounder/vilib/blob/picamera2/examples/record_video.py to set higher resolution when recording video on pidog

So doing this:
Vilib.rec_video_set["framesize"] = (1296, 972)

The output file is empty. If I set it back to 640x480 - no issues, file is recorded.

**Comment by Lovmong** [comment]
I'm sorry, I just saw your question. I added the camera_size parameter temporarily to set the size of the camera view so you can record videos normally. Later, I will optimize other functions for different sizes.(https://github.com/sunfounder/vilib/commit/8e83d354fb82a148b4658c9b9e08980d23f63899)
