### ISSUE TITLE
Compatibility for Bullseye

### ISSUE THREAD

**Issue by DanMan32** [sunfounder/vilib#5]
Bullseye has been out for a year now, it's time to get ViLib and all dependent applications compatible with it.
It seems this shouldn't be too difficult for those very familiar with Pi, Linux and Pi's camera functions.  The heart of it all appears to be in using PiCamera2 rather than PiCamera, possibly also cv2.

**Comment by emannersvip** [comment]
If this project is taking merge requests I'd be happy to submit my code updates  for Bullseye.

**Comment by Lovmong** [comment]
> If this project is taking merge requests I'd be happy to submit my code updates for Bullseye.

Yes, we are happy to receive your pull request. For bullseye or newer bookworm systems, we use the new branch picamera2, please submit your code to the picamera2 branch.
