### ISSUE TITLE
Cloned picamera2, several bugs.

### ISSUE THREAD

**Issue by Gerald-Meyers** [sunfounder/vilib#6]
following install guide from [here](https://docs.sunfounder.com/projects/picrawler-cn/en/latest/python/python_start/download_and_run_code.html).

I found out that the original repository wasn't compatible with my pi4 (64-bit vs 32-bit), so following instructions I modified the code to clone the picamera2 repository (git clone -b picamera2 https://github.com/sunfounder/vilib.git). This works until I get to the `install.py` command.

I first get the error:
    Traceback (most recent call last):
      File "/home/pi/vilib/install.py", line 9, in <module>
        user_name = os.getlogin()
    OSError: [Errno 6] No such device or address
So I change the line `user_name = os.getlogin()` to `user_name = os.getenv('USER')`. This seems to work. 

Then I get the error
    Start installing vilib 0.1.0 for user root
    Python version: 3.9.2
    Raspbian version: 11 (64bit)
    
    Traceback (most recent call last):
      File "/home/pi/vilib/install.py", line 188, in <module>
        elif os_bit == 64 and raspbain_version >= 11:
    TypeError: '>=' not supported between instances of 'str' and 'int'
I verify that yes indeed the `raspbain_version` variable is a string. I make the corresponding change `elif os_bit == 64 and int(raspbain_version) >= 11:`

**Comment by Gerald-Meyers** [comment]
With these two changes (as well as the different repository) the install script successfully completed.

**Comment by Lovmong** [comment]
The problem has been fixed. This issue will be closed.
